SET SCHEMA court;

CREATE TABLE PROSECUTOR (
    ID varchar(255) primary key,
    NAME varchar(255)
);

CREATE TABLE PROCURATORATE (
    ID varchar(255) primary key,
    NAME varchar(255)
);

CREATE TABLE PROCURATORATE_PROSECUTORS (
    PROCURATORATE_ID varchar(255) primary key,
    PROSECUTORS_ID varchar(255),
    CONSTRAINT FK_PROCURATORATE_PROSECUTORS_PROCURATORATE_ID FOREIGN KEY (PROCURATORATE_ID) REFERENCES PROCURATORATE (ID),
    CONSTRAINT FK_PROCURATORATE_PROSECUTORS_PROSECUTORS_ID FOREIGN KEY (PROSECUTORS_ID) REFERENCES PROCURATORATE (ID)
);

CREATE TABLE CRIMINAL_ELEMENTS (
    ID varchar(255) primary key,
    OBJECTIVE_ELEMENT_DESCRIPTION varchar(255),
    SUBJECTIVE_ELEMENT_DESCRIPTION varchar(255)
);

CREATE TABLE CRIMINAL_CASE (
    ID varchar(255) primary key,
    NAME varchar(255) not null,
    TIME bigint not null,
    CRIMINAL_ELEMENTS_ID varchar(255),
    PROCURATORATE_ID varchar(255),
    CONSTRAINT FK_CRIMINAL_CASE_CRIMINAL_ELEMENTS_ID FOREIGN KEY (CRIMINAL_ELEMENTS_ID) REFERENCES CRIMINAL_ELEMENTS (ID),
    CONSTRAINT FK_CRIMINAL_CASE_PROCURATORATE_ID FOREIGN KEY (PROCURATORATE_ID) REFERENCES PROCURATORATE (ID)
);